/*
Magnitude Analysis
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.
*/

-- Find total customers by countries
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;

-- What is the total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

/*
Geographic Distribution
- United States dominates with 7,482 customers, representing the largest market share
- Australia is second with 3,591 customers
- European markets show strong presence:
	+ UK: 1,913 customers
	+ France: 1,810 customers
	+ Germany: 1,780 customers
- Canada has 1,571 customers
- About 337 customer records have missing country data (n/a)

Gender Distribution
- Nearly balanced gender distribution:
	+ Male: 9,341 customers
	+ Female: 9,128 customers
- Only 15 records have missing gender information

Product Analysis
Product Categories
- Components has the most products (127), followed by Bikes (97)
- Clothing (35) and Accessories (29) have fewer product options
- 7 products are uncategorized (NULL)

Pricing
- Bikes are the most expensive category with average cost of $949
- Components average $264
- Unclassified products average $28

Sales Performance
Revenue by Category
- Bikes generate the most revenue ($28,316,272), dominating sales

Sales by Country
- United States leads in items sold (20,481)
- Australia is second with 13,346 items
- Canada (7,630), UK (6,910), Germany (5,626), and France (5,559) follow
- 871 sales have no country data

Key Insights
- Market Concentration: The US and Australia account for the majority of customers and sales
- Product Strategy: Bikes drive revenue despite having fewer products than Components, suggesting higher value per unit
- Pricing Tiers: Clear segmentation between premium (Bikes), mid-range (Components), and budget (Clothing/Accessories) products
- Data Quality: Small but notable missing data in country (337), gender (15), and product category (7) fields
- Gender Neutrality: Nearly equal male and female customer base suggests products appeal broadly

Recommendations
- Focus marketing efforts on the US and Australian markets where customer base is strongest
- Consider expanding the bike product line given its revenue dominance
- Investigate why Components have many products but relatively low revenue contribution
- Implement data cleaning to reduce missing country, gender, and category information
- Explore opportunities to increase sales of accessories and clothing given their lower average costs but revenue potential

*/